### ISSUE TITLE
it can't display electronic signatures,

### ISSUE THREAD

**Issue by nicholaseen** [majkimester/PdfiumViewer.WPF#1]
Overall, it's pretty good, but it can't display electronic signatures,like this picture， Can you reply to me quickly，my email 250693139@qq.com
![yinzhang](https://github.com/majkimester/PdfiumViewer.WPF/assets/31470252/a1e1600a-b3bd-4f9c-80ee-c80c7fb75d94)

**Comment by majkimester** [comment]
Hi, try to add the annotation flag to render flags:

Renderer.Flags |= PdfRenderFlags.Annotations ;
