### ISSUE TITLE
Missing code in the demo xaml

### ISSUE THREAD

**Issue by pcinfogmach** [majkimester/PdfiumViewer.WPF#3]
I wanted to share a small improvement for the window resources. You can enhance functionality by adding the following two lines:

<converters:StringToIntConverter x:Key="StringToIntConverter"/>
<converters:BoolToVisibilityConverter x:Key="BoolToVisibilityConverter"/>

I discovered this while converting the window into a UserControl and referencing it in another project of mine. Generally, it might be better for the demo to use a UserControl instead of a window so that it can be easily integrated into other projects.

Many Thanks for the time you have put into this it is of great value to my project.

**Comment by majkimester** [comment]
These two converters with others are already part of the App.xaml, and so they can be used in any window of the app. This app is only for demo purpose, it is not my goal to provide reusable user control as everybody has different needs. I also created one for my purposes with lot of custom components, so it is not shareable as is.
![usercontrol](https://github.com/user-attachments/assets/1cc2ceb5-539f-4b7a-b8c7-5ddedac79d78)
