### ISSUE TITLE
Improved colorization of search results

### ISSUE THREAD

**Issue by pcinfogmach** [majkimester/PdfiumViewer.WPF#5]
I would like to suggest making the marking color of search results more transparent for improved readability. Here’s a proposed change:

```
CurrentMatchColor = System.Windows.Media.Color.FromArgb(128,
    SystemColors.HighlightColor.R,
    SystemColors.HighlightColor.G,
    SystemColors.HighlightColor.B);

MatchColor = System.Windows.Media.Color.FromArgb(128,
    Colors.Yellow.R,
    Colors.Yellow.G,
    Colors.Yellow.B);
```

This adjustment will enhance the readability of search results, as the current marking makes it difficult to discern the text in some fonts.

**Comment by majkimester** [comment]
The CurrentMatchColor and MatchColor attributes were used with .7 opacity to highlight results. I updated the oppacity to .5 to enhance the readability of search results.
