### ISSUE TITLE
Handling Very Large Files

### ISSUE THREAD

**Issue by pcinfogmach** [majkimester/PdfiumViewer.WPF#6]
I’ve observed that loading very large files significantly slows down the program and causes the entire UI to become unresponsive. Is there a way to address this issue?

Thank you!

**Comment by majkimester** [comment]
Could you please shere an example with me?
I tested it with a 1300 pages book (normal PDF 33MB) and also about 190MB pdf from scanned images. No issue was observed here to load them.

Anyway, you can call the OpenPdf in async way like bellow to avoid blocking the UI thread:

```
    await Task.Run(() =>
    {
        // Any slow operation, e.g:    
        // Renderer.OpenPdf( ... )
    });
```
